my_string = input('Здравствуйте! Где вы проживаете?')
print(len(my_string))
print('Ваш город',my_string)
print('Здравствуйте! Где вы проживаете?'.upper())
print('Здравствуйте! Где вы проживаете?'.lower())
print(my_string.replace(' ', ''))
print(my_string[0])
print(my_string[-1])
